/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import javax.swing.JOptionPane;
import static GUI.FPrincipal.*;
import clases.Categoria;
import clases.Jaula;
import clases.Animal;
import java.net.URL;
import javax.swing.ImageIcon;


/**
 *
 * @author Dickson
 */
public class AgAnimal extends javax.swing.JFrame {

    /**
     * Creates new form AgAnimal
     */
    public AgAnimal() {
        initComponents();
        ListaGuardia.soloNumeros(c1);
        this.setTitle("Agregar Animal");
        
        URL url = getClass().getResource("/Img/4.png");
        ImageIcon img =new ImageIcon(url);
        setIconImage(img.getImage());
        
              
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        c1 = new javax.swing.JTextField();
        categoriaCombo = new javax.swing.JComboBox();
        animalCombo = new javax.swing.JComboBox();
        jaulaCombo = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        fechaEntrada = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(151, 193, 225));

        jLabel1.setText("Animal");

        jLabel2.setText("IdAnimal");

        jLabel3.setText("Categoria:");

        jLabel4.setText("Animal");

        jLabel5.setText("Jaula");

        jLabel6.setText("Fecha");

        categoriaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaComboActionPerformed(evt);
            }
        });

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(animalCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(categoriaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jaulaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(categoriaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(animalCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(20, 20, 20)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jaulaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(fechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (!c1.getText().isEmpty())
        {
            int a1=categoriaCombo.getSelectedIndex();
            if (a1 != -1)
            {
                int a2=animalCombo.getSelectedIndex();
                if (a2 != -1)
                {
                    int a3=jaulaCombo.getSelectedIndex();
                    if (a3 != -1)
                    {
                        if (fechaEntrada.getDate() != null)
                        {
                            String seleccionCategoria = (String)categoriaCombo.getSelectedItem();
                            java.util.StringTokenizer st = new java.util.StringTokenizer(seleccionCategoria, "-");
                            String cat = st.nextToken();  //id Categoria                         
                            String nombre_categoria= st.nextToken();//Nombre Categoria

                            String seleccionAnimal = (String)animalCombo.getSelectedItem();//Nombre Animal

                            Long seleccionJaula = (Long)jaulaCombo.getSelectedItem();//idJaula

                            //Introduciendo Animal:

                            Jaula p = ListaJaula.cabJau;

                            while (p != null)
                            {
                                if (p.getIdJaula() == seleccionJaula)
                                {
                                    Animal a= new Animal();
                                    a.setIdAnimal(Long.parseLong(c1.getText().trim()));
                                    a.setCategoria(cat);//Id Categoria
                                    a.setNombreCategoria(nombre_categoria);
                                    a.setNombreAnimal(seleccionAnimal);
                                    a.setFechaEntrada(fechaEntrada.getDate());
                                    p.listaA.add(a);
                                    JOptionPane.showMessageDialog(null, "Animal Añadido A Jaula Exitosamente...");
                                    refrescar();
                                    break;
                                }
                                p = p.sig;         
                            }   
                        }
                        else
                            JOptionPane.showMessageDialog(null, "Ingrese la Fecha de Entrada");
                    }
                    else
                        JOptionPane.showMessageDialog(null, "Seleccione La Jaula");
                }
                else
                    JOptionPane.showMessageDialog(null, "Seleccione El Animal");
                
            }
            else
                JOptionPane.showMessageDialog(null, "Seleccione Categoria");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Escriba Id Animal");
            c1.requestFocus();
        }
            
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void categoriaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaComboActionPerformed


        //Para mostrar los animales en el jcombobox
        animalCombo.removeAllItems(); 

        String seleccion = (String)categoriaCombo.getSelectedItem();

        java.util.StringTokenizer st = new java.util.StringTokenizer(seleccion.trim(), "-");

        String token = (String) st.nextToken();
        long num= Long.parseLong(token);

        listadoComboAnimal(num);
      


    }//GEN-LAST:event_categoriaComboActionPerformed

    void refrescar()
    {
        c1.setText(null);
        fechaEntrada.setDate(null);
        categoriaCombo.setSelectedIndex(0);
        animalCombo.setSelectedIndex(0);
        jaulaCombo.setSelectedIndex(0);
    }
    
    //Metodo para cargar los animales en el jcombobox con el id de la categoria
    void listadoComboAnimal(long seleccion)
    {
        Categoria c = ListaCategoria.cabCat;
        
        while ( c != null)
        {
            if (c.getIdCategoria() == seleccion)
            {
                for (int j=0; j<c.animalesCategoria.size(); j++)
                {
                    String animal = (String)c.animalesCategoria.get(j);
                    animalCombo.addItem(animal);
                }
                break;
            }
            
            c = c.sig;
        }        
    }    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgAnimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox animalCombo;
    private javax.swing.JTextField c1;
    public static javax.swing.JComboBox categoriaCombo;
    private com.toedter.calendar.JDateChooser fechaEntrada;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JComboBox jaulaCombo;
    // End of variables declaration//GEN-END:variables
}
