/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static GUI.CrearCategoria.idcategoriacombo;
import static GUI.CrearJaula.guardia;
import java.net.URL;
import javax.swing.ImageIcon;
import clases.*;
import javax.swing.*;

/**
 *
 * @author Dickson
 */
public class FPrincipal extends javax.swing.JFrame {
    
    public static clases.ListaL_Guardia ListaGuardia;
    public static clases.Guardia guar;
    
    public static clases.ListaL_Jaula ListaJaula;
    public static clases.Jaula jau;
    
    public static clases.ListaL_Categoria ListaCategoria;
    public static clases.Categoria cat;
    
    public static clases.ListaL_Traslado ListaTraslado;
    public static clases.Traslado tras;
    
   // public static clases.ListaL_Animal Lista;
    
    
    

    /**
     * Creates new form FPrincipal
     */
    public FPrincipal() {
        
        initComponents();
        
        ListaGuardia = new ListaL_Guardia();
        ListaGuardia.crearLista();
        
        ListaJaula = new ListaL_Jaula();
        ListaJaula.crearLista();
        
        ListaCategoria = new ListaL_Categoria();
        ListaCategoria.crearLista();
        
        ListaTraslado = new ListaL_Traslado();
        ListaTraslado.crearLista();
      
        this.setTitle("Zoologico");
        
        URL url = getClass().getResource("/Img/4.png");
        ImageIcon img =new ImageIcon(url);
        setIconImage(img.getImage());
        
         System.setProperty("awt.useSystemAAFontSettings","on");
         System.setProperty("swing.aatext", "true");
      
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuAnimales = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        menuGuardias = new javax.swing.JPopupMenu();
        jMenu2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuCategorias = new javax.swing.JPopupMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        menuTraslados = new javax.swing.JPopupMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jMenuItem1.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        jMenuItem1.setText("Agregar Animal A Jaula");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuAnimales.add(jMenuItem1);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte.png"))); // NOI18N
        jMenu1.setText("Reportes Animales");
        jMenu1.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N

        jMenuItem8.setText("Todos Los Animales");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem9.setText("Segun Tipo");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuItem2.setText("Segun Jaula");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem10.setText("Segun Guardia");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuItem7.setText("Traslados Segun Categoria");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem11.setText("Traslados Segun Rango de Fecha");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        menuAnimales.add(jMenu1);

        jMenu2.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        jMenu2.setText("Agregar Guardias");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        menuGuardias.add(jMenu2);

        jMenuItem3.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte.png"))); // NOI18N
        jMenuItem3.setText("Reporte Guardias");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuGuardias.add(jMenuItem3);

        jMenuItem6.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        jMenuItem6.setText("Agregar Categorias");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menuCategorias.add(jMenuItem6);

        jMenuItem5.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        jMenuItem5.setText("Trasladar Animal de Jaula");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menuTraslados.add(jMenuItem5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(151, 193, 225));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/07_1.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setFocusable(false);
        jLabel1.setName(""); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/zol_1.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/leon.png"))); // NOI18N
        jLabel3.setToolTipText("Animales\n");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tombo.png"))); // NOI18N
        jLabel4.setToolTipText("Guardias");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel4MouseReleased(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorias.png"))); // NOI18N
        jLabel7.setToolTipText("Categorias");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jaula.png"))); // NOI18N
        jLabel6.setToolTipText("Jaulas");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jjj.png"))); // NOI18N
        jLabel5.setToolTipText("Traslados");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel4)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel6))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jLabel7)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel5))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
  
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

        menuAnimales.show(evt.getComponent(), evt.getX(), evt.getY());
        
        
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked

        menuGuardias.show(evt.getComponent(), evt.getX(), evt.getY());
        

    }//GEN-LAST:event_jLabel4MouseClicked

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
       
        new CrearGuardia().setVisible(true);
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        Guardia j = ListaGuardia.cabGuar;
        
        if (j != null)//Averiguar si hay guardias en la Lista
           new ListadoGuardias().setVisible(true);
        else
            JOptionPane.showMessageDialog(null, "Debe Agregar Guardias Primero");
 
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jLabel4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseReleased
      


    }//GEN-LAST:event_jLabel4MouseReleased

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        

        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        Jaula j = ListaJaula.cabJau;//Cabeza de ListaJaula
        
        if (j != null)//Pregunta si hay nodos en la Ll
        {
            new AgAnimal().setVisible(true);
            listado_combo_jaula();//Carga jComboBox de jaulas en AgAnimal.java
            listado_combo_categoria_animal();//Carga jComboBox de categorias en AgAnimal.java  
        }
        else
            JOptionPane.showMessageDialog(null, "Debe Crear Jaulas y Adicionar Animales"); 

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed

        Jaula j = ListaJaula.cabJau;
        
        if (j != null)
        {
            if (! j.listaA.isEmpty())
            {                
                new ReporteAnimals().setVisible(true);
            }
            else
            JOptionPane.showMessageDialog(null, "Debe Agregar Animales a Jaulas");    
        }
        else
            JOptionPane.showMessageDialog(null, "Debe Crear Jaulas y Adicionar Animales"); 
            
   
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        
        Jaula j = ListaJaula.cabJau;
        
        if (j != null)
        {
            if (! j.listaA.isEmpty())
            {                
                new ReporteAnimalsTipo().setVisible(true);
                listado_combo_tipo_animal();
            }
            else
            JOptionPane.showMessageDialog(null, "Debe Agregar Animales a Jaulas");    
        }
        else
            JOptionPane.showMessageDialog(null, "Debe Crear Jaulas y Adicionar Animales"); 
       
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        Jaula j = ListaJaula.cabJau;
        
        if (j != null)
        {
            if (! j.listaA.isEmpty())
            {                
                new ReporteJaula().setVisible(true);
                listado_tipo_combo_jaula();
            }
            else
            JOptionPane.showMessageDialog(null, "Debe Agregar Animales a Jaulas");    
        }
        else
            JOptionPane.showMessageDialog(null, "Debe Crear Jaulas y Adicionar Animales"); 
 
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed


        Jaula j = ListaJaula.cabJau;
        
        if (j != null)
        {
            if (! j.listaA.isEmpty())
            {                
                new ReporteGuardia().setVisible(true);
                listado_combo_guardias();
            }
            else
            JOptionPane.showMessageDialog(null, "Debe Agregar Animales a Jaulas");    
        }
        else
            JOptionPane.showMessageDialog(null, "Debe Crear Jaulas y Adicionar Animales"); 

    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed

        
        Jaula j = ListaJaula.cabJau;
        
        if (j != null)
        {
            new Traslados().setVisible(true);
            listado_combo_jaula_tras();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Debe Crear Jaulas Primero");
        }

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed

        Jaula j = ListaJaula.cabJau;
        
        Traslado t = ListaTraslado.cabTras;
        
        if (t != null)
        {
            new ReporteTraslados().setVisible(true);
                listado_combo_tipo_traslado();
        }
        else
            JOptionPane.showMessageDialog(null, "Primero se deben hacer traslados"); 


    }//GEN-LAST:event_jMenuItem7ActionPerformed

   
    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed


            
        
        Jaula j = ListaJaula.cabJau;
        
        Traslado t = ListaTraslado.cabTras;
        
        if (t != null)
            new ReporteRangoFechas().setVisible(true);
        else
            JOptionPane.showMessageDialog(null, "Primero se deben hacer traslados"); 


    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Jaula j = ListaJaula.cabJau;
        
        if (j != null)
        {
            if (! j.listaA.isEmpty())
            {                
                new Traslados().setVisible(true);
                listado_combo_jaula_tras();
            }
            else
            JOptionPane.showMessageDialog(null, "Debe Agregar Animales a Jaulas");    
        }
        else
            JOptionPane.showMessageDialog(null, "Debe Crear Jaulas y Adicionar Animales"); 
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        
        Guardia g = ListaGuardia.cabGuar;
        
        if (g != null)
        {
            new CrearJaula().setVisible(true);
            listado_combo();//Llena el jcombobox de crear jaula
            CrearJaula.guardia.setSelectedItem(null);
        }
        else
            JOptionPane.showMessageDialog(null, "Debe crear Guardias Primero");
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        
        Categoria w = ListaCategoria.cabCat;
        
        if (w == null)
            new CrearCategoria().setVisible(true); 
      
        else
        {
            new CrearCategoria().setVisible(true);
            while (w != null)
            {
                idcategoriacombo.addItem(w.getIdCategoria()+ "-" + w.getNombreCategoria());
                w = w.sig;
            }        
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    
    
    public void listado_combo_jaula_tras()
    {
        
        Jaula j = ListaJaula.cabJau;
        
        while (j != null)
        {
            Traslados.jaulaComboFuente.addItem(j.getIdJaula());
            Traslados.jaulaComboDestino.addItem(j.getIdJaula());
             
            j = j.sig;
        }
       
    }  

    
    
    public void listado_combo_tipo_animal()
    {
        Categoria p = ListaCategoria.cabCat;
        
        while (p != null)
        {
            ReporteAnimalsTipo.tipoCombo.addItem(p.getIdCategoria()+ "-" + p.getNombreCategoria());      
            p = p.sig;
        }
        
    }
    public void listado_combo_tipo_traslado()
    {
        Categoria p = ListaCategoria.cabCat;
        
        while (p != null)
        {
            ReporteTraslados.tipoCombo.addItem(p.getIdCategoria()+ "-" + p.getNombreCategoria());      
            p = p.sig;
        }
        
    }
    
    public void listado_tipo_combo_jaula()
    {    
      Jaula p = ListaJaula.cabJau;
      
      while (p != null)
      {
          ReporteJaula.jaulaCombo.addItem(p.getIdJaula());
          p = p.sig;
      }            
    }    
    
      
    public void listado_combo_guardias()
    {
        Guardia p = ListaGuardia.cabGuar;
        
        while ( p!= null)
        {
            ReporteGuardia.guardiaCombo.addItem(p.getCedula_guardia() + " - " + p.getNombre_guardia());
            p = p.sig;
        }
            
    }
    
    
    
    //Combo guardia de guardia
    public void listado_combo()
    {
        Guardia p = ListaGuardia.cabGuar;         
        while ( p != null)
        {
            guardia.addItem(p.getCedula_guardia() + "-" + p.getNombre_guardia());
            p=p.sig;                    
        }   
    }
    
    //Combo categoria de CrearCategoria
    public void listado_combo_categoria()
            
    {
        Categoria c = ListaCategoria.cabCat;
        
        while ( c != null)
        {
            CrearCategoria.idcategoriacombo.addItem(c.getIdCategoria()+ "-" + c.getNombreCategoria());
            c = c.sig;
        }           
    }
    
    //Combo categoria de AgAnimal
    public void listado_combo_categoria_animal()
    {
        Categoria c = ListaCategoria.cabCat;
        
        while ( c != null)
        {
            AgAnimal.categoriaCombo.addItem(c.getIdCategoria()+ "-" + c.getNombreCategoria());
            c = c.sig;
        }           
    }
    
    //Combo ListaJaulas de AgAnimal
    public void listado_combo_jaula()
    {     
        Jaula j = ListaJaula.cabJau;        
        while ( j != null)
        {
            AgAnimal.jaulaCombo.addItem(j.getIdJaula());
            j = j.sig;
        }               
    }
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu menuAnimales;
    private javax.swing.JPopupMenu menuCategorias;
    private javax.swing.JPopupMenu menuGuardias;
    private javax.swing.JPopupMenu menuTraslados;
    // End of variables declaration//GEN-END:variables
}
